# Generated by Django 5.2.13 on 2026-04-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alumniaccount',
            name='users_alumn_student_9d0010_idx',
        ),
        migrations.RemoveField(
            model_name='alumniaccount',
            name='student_number',
        ),
        migrations.AddIndex(
            model_name='alumniaccount',
            index=models.Index(fields=['account_status'], name='users_alumn_account_677b1e_idx'),
        ),
    ]
