# Generated by Django 5.2.13 on 2026-04-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_alumniaccount_users_alumn_student_9d0010_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduatemasterrecord',
            options={'ordering': ['full_name']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE users_graduatemasterrecord DROP COLUMN IF EXISTS student_number CASCADE;',
                    reverse_sql='ALTER TABLE users_graduatemasterrecord ADD COLUMN IF NOT EXISTS student_number varchar(50);',
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='graduatemasterrecord',
                    name='users_gradu_student_e2e390_idx',
                ),
                migrations.RemoveField(
                    model_name='graduatemasterrecord',
                    name='student_number',
                ),
            ],
        ),
    ]
