# Generated by Django 5.2.13 on 2026-04-13 18:05

from django.db import migrations


def _drop_student_number_column(apps, schema_editor):
    """Drop legacy student_number column in a database-safe way."""
    table_name = "users_graduatemasterrecord"
    vendor = schema_editor.connection.vendor

    if vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE users_graduatemasterrecord DROP COLUMN IF EXISTS student_number CASCADE;"
        )
        return

    if vendor == "sqlite":
        # SQLite cannot safely drop this legacy UNIQUE column in place.
        # Keep DB migration as a no-op; state migration still removes the field from Django.
        return


def _restore_student_number_column(apps, schema_editor):
    """Reverse operation for legacy compatibility on rollback."""
    table_name = "users_graduatemasterrecord"
    vendor = schema_editor.connection.vendor

    if vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE users_graduatemasterrecord ADD COLUMN IF NOT EXISTS student_number varchar(50);"
        )
        return

    if vendor == "sqlite":
        # Reverse is also a no-op for SQLite for compatibility with existing local DBs.
        return


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_alumniaccount_users_alumn_student_9d0010_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduatemasterrecord',
            options={'ordering': ['full_name']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=_drop_student_number_column,
                    reverse_code=_restore_student_number_column,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='graduatemasterrecord',
                    name='users_gradu_student_e2e390_idx',
                ),
                migrations.RemoveField(
                    model_name='graduatemasterrecord',
                    name='student_number',
                ),
            ],
        ),
    ]
