# Generated by Django 5.2.13 on 2026-04-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_graduatemasterrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeraccount',
            name='profile_json',
            field=models.TextField(blank=True),
        ),
    ]
