# Generated by Django 5.2.13 on 2026-04-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_employeraccount_profile_json'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alumniaccount',
            new_name='users_alumn_account_e0bd8c_idx',
            old_name='users_alumn_account_677b1e_idx',
        ),
        migrations.RenameIndex(
            model_name='employeraccount',
            new_name='users_emplo_company_5e7d75_idx',
            old_name='users_emplo_company_e0cf74_idx',
        ),
        migrations.RenameIndex(
            model_name='graduatemasterrecord',
            new_name='users_gradu_batch_y_7f0cc1_idx',
            old_name='users_gradu_batch_y_a1190e_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='users_account_groups', help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, db_table='users_account_permissions', help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterModelTable(
            name='admincredential',
            table='users_admin_credentials',
        ),
        migrations.AlterModelTable(
            name='alumniaccount',
            table='users_alumni_accounts',
        ),
        migrations.AlterModelTable(
            name='employeraccount',
            table='users_employer_accounts',
        ),
        migrations.AlterModelTable(
            name='graduatemasterrecord',
            table='users_graduate_master_records',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_accounts',
        ),
    ]
