# Generated by Django 5.2.13 on 2026-04-15 08:48

import json

from django.db import migrations, models


def _backfill_normalized_user_fields(apps, schema_editor):
    EmployerAccount = apps.get_model("users", "EmployerAccount")
    AlumniAccount = apps.get_model("users", "AlumniAccount")

    for employer in EmployerAccount.objects.all().iterator():
        profile = {}
        raw_profile = getattr(employer, "profile_json", "")
        if raw_profile:
            try:
                parsed = json.loads(raw_profile)
                if isinstance(parsed, dict):
                    profile = parsed
            except (TypeError, ValueError):
                profile = {}

        changed_fields = []
        if not employer.industry and isinstance(profile.get("industry"), str):
            employer.industry = profile.get("industry", "").strip()
            changed_fields.append("industry")
        if not employer.contact_name and isinstance(profile.get("contact_name"), str):
            employer.contact_name = profile.get("contact_name", "").strip()
            changed_fields.append("contact_name")
        if not employer.contact_position and isinstance(profile.get("position"), str):
            employer.contact_position = profile.get("position", "").strip()
            changed_fields.append("contact_position")
        if not employer.company_website and isinstance(profile.get("website"), str):
            employer.company_website = profile.get("website", "").strip()
            changed_fields.append("company_website")
        if not employer.company_phone and isinstance(profile.get("phone"), str):
            employer.company_phone = profile.get("phone", "").strip()
            changed_fields.append("company_phone")
        if not employer.company_address and isinstance(profile.get("address"), str):
            employer.company_address = profile.get("address", "").strip()
            changed_fields.append("company_address")

        if changed_fields:
            employer.save(update_fields=changed_fields)

    for alumni in AlumniAccount.objects.all().iterator():
        if alumni.master_record_id:
            alumni.match_status = "matched"
            if alumni.matched_at is None:
                alumni.matched_at = alumni.created_at
            alumni.save(update_fields=["match_status", "matched_at"])
        elif alumni.match_status == "pending":
            alumni.match_status = "unmatched"
            alumni.save(update_fields=["match_status"])


def _reverse_backfill_normalized_user_fields(apps, schema_editor):
    EmployerAccount = apps.get_model("users", "EmployerAccount")

    for employer in EmployerAccount.objects.all().iterator():
        profile = {
            "industry": employer.industry,
            "website": employer.company_website,
            "contact_name": employer.contact_name,
            "position": employer.contact_position,
            "phone": employer.company_phone,
            "address": employer.company_address,
        }
        employer.profile_json = json.dumps(profile)
        employer.save(update_fields=["profile_json"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_users_alumn_account_677b1e_idx_users_alumn_account_e0bd8c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniaccount',
            name='match_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('broken', 'Broken')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='alumniaccount',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeraccount',
            name='company_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employeraccount',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employeraccount',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employeraccount',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employeraccount',
            name='contact_position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employeraccount',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(
            code=_backfill_normalized_user_fields,
            reverse_code=_reverse_backfill_normalized_user_fields,
        ),
        migrations.RemoveField(
            model_name='employeraccount',
            name='profile_json',
        ),
        migrations.RemoveField(
            model_name='graduatemasterrecord',
            name='email',
        ),
        migrations.AddIndex(
            model_name='alumniaccount',
            index=models.Index(fields=['match_status'], name='users_alumn_match_s_a183c4_idx'),
        ),
    ]
