# Generated by Django 5.2.13 on 2026-04-19 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_employeraccount_profile_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniaccount',
            name='biometric_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='alumniaccount',
            name='face_photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('middle_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('birth_date', models.CharField(blank=True, max_length=10)),
                ('civil_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('graduation_date', models.CharField(blank=True, max_length=10)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scholarship', models.CharField(blank=True, max_length=120)),
                ('highest_attainment', models.CharField(blank=True, choices=[('NA', 'None / Undergraduate'), ('Graduate', 'College Graduate'), ('PostGrad', 'Post-Graduate'), ('Doctorate', 'Doctorate')], max_length=20)),
                ('graduate_school', models.CharField(blank=True, max_length=255)),
                ('prof_eligibility', models.CharField(blank=True, max_length=255)),
                ('prof_eligibility_other', models.CharField(blank=True, max_length=255)),
                ('awards', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.alumniaccount')),
            ],
            options={
                'db_table': 'users_alumni_profiles',
            },
        ),
        migrations.CreateModel(
            name='FaceScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('face_front', 'Front'), ('face_left', 'Left'), ('face_right', 'Right'), ('login', 'Login')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_scans', to='users.alumniaccount')),
            ],
            options={
                'db_table': 'users_face_scans',
                'indexes': [models.Index(fields=['alumni', 'scan_type'], name='users_face__alumni__f88d91_idx'), models.Index(fields=['alumni', 'created_at'], name='users_face__alumni__528aba_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('scan_url', models.URLField(blank=True, max_length=500)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('descriptor_distance', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_audits', to='users.alumniaccount')),
            ],
            options={
                'db_table': 'users_login_audits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['alumni', 'timestamp'], name='users_login_alumni__874af1_idx')],
            },
        ),
    ]
