# Generated by Django 5.2.13 on 2026-04-21 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_alumniaccount_biometric_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='academic_honors',
            field=models.IntegerField(blank=True, choices=[(1, 'None'), (2, 'Cum Laude'), (3, 'Magna Cum Laude'), (4, 'Summa Cum Laude')], help_text='Academic honors for regression model', null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='english_proficiency',
            field=models.IntegerField(blank=True, choices=[(1, 'Basic'), (2, 'Conversational'), (3, 'Professional/Business')], help_text='English proficiency level', null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='general_average_range',
            field=models.IntegerField(blank=True, choices=[(0, 'Below 75'), (1, '75-79'), (2, '80-84'), (3, '85-89'), (4, '90-94'), (5, '95-100')], help_text='GPA range encoding for regression model', null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='has_portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='ojt_relevance',
            field=models.IntegerField(blank=True, choices=[(0, 'Not applicable'), (1, 'Not related'), (2, 'Somewhat related'), (3, 'Yes, directly related')], help_text='OJT relevance to BSIS degree', null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='prior_work_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='professional_certifications',
            field=models.JSONField(blank=True, default=list, help_text='Array of professional certification strings'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='soft_skill_count',
            field=models.IntegerField(default=0, help_text='Count of soft skills selected (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='technical_skill_count',
            field=models.IntegerField(default=0, help_text='Count of technical skills selected (0-12)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
