# Generated by Django 5.2.13 on 2026-05-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_loginaudit_gps_and_retracking_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='further_studies_status',
            field=models.CharField(blank=True, choices=[('none', "Bachelor's only"), ('enrolled', 'Currently enrolled in further studies'), ('completed', 'Completed further studies')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='postgrad_field',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='postgrad_program',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='postgrad_school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='postgrad_year_completed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='postgrad_year_started',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
