# Generated by Django 5.2.13 on 2026-05-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alumniprofile_further_studies_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='github_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
