# Generated by Django 5.2.13 on 2026-05-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0008_verificationdecision_evaluation_fields'),
        ('users', '0012_alumniprofile_github_url_alumniprofile_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeraccount',
            name='desired_skills',
            field=models.ManyToManyField(blank=True, related_name='employer_accounts_wanting', to='tracer.skill'),
        ),
    ]
