# Generated by Django 5.2.13 on 2026-05-11 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_employeraccount_desired_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttemptThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=320, unique=True)),
                ('role', models.CharField(max_length=10)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('lockout_until', models.DateTimeField(blank=True, null=True)),
                ('lockout_tier', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_login_attempt_throttle',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('graduate', 'Graduate'), ('employer', 'Employer')], max_length=10)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'users_password_reset_codes',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['email', 'role', 'used_at'], name='users_passw_email_8cc829_idx'), models.Index(fields=['sent_at'], name='users_passw_sent_at_1a524e_idx')],
            },
        ),
    ]
