# Generated by Django 5.2.13 on 2026-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_loginattemptthrottle_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='role',
            field=models.CharField(choices=[('graduate', 'Graduate'), ('employer', 'Employer'), ('admin', 'Admin')], max_length=10),
        ),
    ]
