# Generated by Django 5.2.13 on 2026-05-19 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_passwordresetcode_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='english_proficiency',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='portfolio_url',
        ),
    ]
