# Generated by Django 5.2.13 on 2026-05-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_english_github_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatemasterrecord',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
