# Generated by Django 5.2.13 on 2026-09-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alumni_consent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='home_barangay',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='home_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='home_is_abroad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='home_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='home_location_accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='home_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='home_region',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
