# Generated by Django 5.2.13 on 2026-09-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alumniprofile_home_barangay_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alumniprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('first_name__regex', '[0-9]'), _negated=True), models.Q(('middle_name__regex', '[0-9]'), _negated=True), models.Q(('last_name__regex', '[0-9]'), _negated=True)), name='profile_names_have_no_digits'),
        ),
        migrations.AddConstraint(
            model_name='alumniprofile',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date', ''), ('birth_date__regex', '^[0-9]{4}-(0[1-9]|1[0-2])$'), _connector='OR'), name='profile_birth_date_is_year_month'),
        ),
        migrations.AddConstraint(
            model_name='alumniprofile',
            constraint=models.CheckConstraint(condition=models.Q(('graduation_date', ''), ('graduation_date__regex', '^[0-9]{4}-(0[1-9]|1[0-2])$'), _connector='OR'), name='profile_graduation_date_is_year_month'),
        ),
        migrations.AddConstraint(
            model_name='graduatemasterrecord',
            constraint=models.CheckConstraint(condition=models.Q(('batch_year__gte', 2000), ('batch_year__lte', 2100)), name='master_batch_year_realistic'),
        ),
        migrations.AddConstraint(
            model_name='graduatemasterrecord',
            constraint=models.CheckConstraint(condition=models.Q(('full_name__regex', '[[:alpha:]]'), models.Q(('full_name__regex', '[0-9]'), _negated=True)), name='master_full_name_is_a_name'),
        ),
    ]
