# Generated by Django 5.2.13 on 2026-09-15 07:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from datetime import timedelta

from django.db import migrations, models


def backfill_history(apps, schema_editor):
    """Seed each graduate's history from the dates already saved, so the History
    tab is not empty for accounts made before it existed. Only dates survive
    (the old columns were overwritten each time), so rows carry no snapshot and
    are marked is_backfilled."""
    AlumniAccount = apps.get_model("users", "AlumniAccount")
    AlumniProfile = apps.get_model("users", "AlumniProfile")
    RetrackingEvent = apps.get_model("users", "RetrackingEvent")

    profiles = {
        p.alumni_id: p
        for p in AlumniProfile.objects.only("alumni_id", "last_retraced_at", "last_retracking_reminder_at")
    }
    rows = []
    for account in AlumniAccount.objects.only("id", "created_at"):
        rows.append(RetrackingEvent(
            alumni_id=account.id, kind="registered", occurred_at=account.created_at, is_backfilled=True,
        ))
        profile = profiles.get(account.id)
        if profile is None:
            continue
        # Registration also stamps last_retraced_at; only a later date is a real confirmation.
        if profile.last_retraced_at and profile.last_retraced_at - account.created_at > timedelta(days=1):
            rows.append(RetrackingEvent(
                alumni_id=account.id, kind="retraced", occurred_at=profile.last_retraced_at, is_backfilled=True,
            ))
        if profile.last_retracking_reminder_at:
            rows.append(RetrackingEvent(
                alumni_id=account.id, kind="reminder", occurred_at=profile.last_retracking_reminder_at,
                is_backfilled=True,
            ))
    RetrackingEvent.objects.bulk_create(rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alumniprofile_last_retraced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('registered', 'Registered'), ('retraced', 'Employment record confirmed'), ('reminder', 'Reminder sent')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employment_status', models.CharField(blank=True, max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('days_since_previous', models.PositiveIntegerField(blank=True, null=True)),
                ('sent_by', models.CharField(blank=True, max_length=254)),
                ('is_backfilled', models.BooleanField(default=False)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retracking_events', to='users.alumniaccount')),
            ],
            options={
                'db_table': 'users_retracking_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['alumni', '-occurred_at'], name='users_retrack_alumni_idx')],
            },
        ),
        migrations.RunPython(backfill_history, migrations.RunPython.noop),
    ]
