# Generated by Django 5.2.13 on 2026-09-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_nullable_preemployment_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrackingevent',
            name='kind',
            field=models.CharField(choices=[('registered', 'Registered'), ('retraced', 'Employment record confirmed'), ('reminder', 'Reminder sent'), ('approved', 'Account approved'), ('rejected', 'Account rejected')], max_length=20),
        ),
    ]
