# Generated by Django 5.2.13 on 2026-09-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_audit_event_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrackingevent',
            name='graduate_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='retrackingevent',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='retrackingevent',
            name='alumni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retracking_events', to='users.alumniaccount'),
        ),
    ]
