# Generated by Django 5.2.13 on 2026-09-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_audit_events_outlive_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatemasterrecord',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
