# Generated by Django 5.2.13 on 2026-04-12 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracer', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniskill',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.alumniaccount'),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='users.alumniaccount'),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='employer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_records', to='users.employeraccount'),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_records', to='tracer.industry'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles', to='tracer.industry'),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_records', to='tracer.jobtitle'),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_records', to='tracer.region'),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='salary_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_records', to='tracer.salaryband'),
        ),
        migrations.AddField(
            model_name='alumniskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_entries', to='tracer.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='tracer.skillcategory'),
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='employer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_decisions', to='users.employeraccount'),
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='employment_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='tracer.employmentrecord'),
        ),
        migrations.AddField(
            model_name='verificationtoken',
            name='employment_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_tokens', to='tracer.employmentrecord'),
        ),
        migrations.AddField(
            model_name='verificationtoken',
            name='graduate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='users.alumniaccount'),
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='tracer.verificationtoken'),
        ),
        migrations.AddIndex(
            model_name='employmentrecord',
            index=models.Index(fields=['verification_status'], name='tracer_empl_verific_69e736_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentrecord',
            index=models.Index(fields=['employment_status'], name='tracer_empl_employm_2a4d00_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentrecord',
            index=models.Index(fields=['alumni', 'is_current'], name='tracer_empl_alumni__49c89d_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentrecord',
            index=models.Index(fields=['industry', 'region'], name='tracer_empl_industr_07dc09_idx'),
        ),
        migrations.AddConstraint(
            model_name='employmentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('alumni',), name='uniq_current_employment_per_alumni'),
        ),
        migrations.AddIndex(
            model_name='alumniskill',
            index=models.Index(fields=['skill', 'proficiency_level'], name='tracer_alum_skill_i_8f7ac2_idx'),
        ),
        migrations.AddConstraint(
            model_name='alumniskill',
            constraint=models.UniqueConstraint(fields=('alumni', 'skill'), name='uniq_alumni_skill'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['graduate', 'status'], name='tracer_veri_graduat_d92445_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['expires_at', 'status'], name='tracer_veri_expires_9558c1_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationdecision',
            index=models.Index(fields=['decision', 'decided_at'], name='tracer_veri_decisio_86c1fe_idx'),
        ),
    ]
