# Generated by Django 5.2.13 on 2026-04-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alumniskill',
            new_name='tracer_alum_skill_i_5c1116_idx',
            old_name='tracer_alum_skill_i_8f7ac2_idx',
        ),
        migrations.RenameIndex(
            model_name='employmentrecord',
            new_name='tracer_empl_verific_163261_idx',
            old_name='tracer_empl_verific_69e736_idx',
        ),
        migrations.RenameIndex(
            model_name='employmentrecord',
            new_name='tracer_empl_employm_440eff_idx',
            old_name='tracer_empl_employm_2a4d00_idx',
        ),
        migrations.RenameIndex(
            model_name='employmentrecord',
            new_name='tracer_empl_alumni__46b7ed_idx',
            old_name='tracer_empl_alumni__49c89d_idx',
        ),
        migrations.RenameIndex(
            model_name='employmentrecord',
            new_name='tracer_empl_industr_827bf6_idx',
            old_name='tracer_empl_industr_07dc09_idx',
        ),
        migrations.RenameIndex(
            model_name='verificationdecision',
            new_name='tracer_veri_decisio_0a42fc_idx',
            old_name='tracer_veri_decisio_86c1fe_idx',
        ),
        migrations.RenameIndex(
            model_name='verificationtoken',
            new_name='tracer_veri_graduat_36ae49_idx',
            old_name='tracer_veri_graduat_d92445_idx',
        ),
        migrations.RenameIndex(
            model_name='verificationtoken',
            new_name='tracer_veri_expires_ed5567_idx',
            old_name='tracer_veri_expires_9558c1_idx',
        ),
        migrations.AlterModelTable(
            name='alumniskill',
            table='tracer_alumni_skills',
        ),
        migrations.AlterModelTable(
            name='employmentrecord',
            table='tracer_employment_records',
        ),
        migrations.AlterModelTable(
            name='industry',
            table='tracer_industries',
        ),
        migrations.AlterModelTable(
            name='jobtitle',
            table='tracer_job_titles',
        ),
        migrations.AlterModelTable(
            name='region',
            table='tracer_regions',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='tracer_skills',
        ),
        migrations.AlterModelTable(
            name='skillcategory',
            table='tracer_skill_categories',
        ),
        migrations.AlterModelTable(
            name='verificationdecision',
            table='tracer_verification_decisions',
        ),
        migrations.AlterModelTable(
            name='verificationtoken',
            table='tracer_verification_tokens',
        ),
    ]
