# Generated by Django 5.2.13 on 2026-04-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentrecord',
            name='salary_band',
        ),
        migrations.DeleteModel(
            name='SalaryBand',
        ),
    ]
