# Generated by Django 5.2.13 on 2026-04-15 08:48

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def _backfill_verification_outputs(apps, schema_editor):
    VerificationDecision = apps.get_model("tracer", "VerificationDecision")
    VerificationToken = apps.get_model("tracer", "VerificationToken")

    for decision in VerificationDecision.objects.select_related("employment_record", "token").all().iterator():
        employment_record = getattr(decision, "employment_record", None)
        if not employment_record:
            continue

        changed_fields = []

        if not decision.token_id:
            token = VerificationToken.objects.create(
                alumni_id=employment_record.alumni_id,
                employment_record_id=employment_record.id,
                expires_at=decision.decided_at or timezone.now(),
                status="used",
                used_at=decision.decided_at,
            )
            decision.token_id = token.token_id
            changed_fields.append("token")

        employer_name_verified = getattr(employment_record, "employer_name_verified", "")
        if employer_name_verified and not decision.verified_employer_name:
            decision.verified_employer_name = employer_name_verified
            changed_fields.append("verified_employer_name")

        if employment_record.job_title_id and not decision.verified_job_title_id:
            decision.verified_job_title_id = employment_record.job_title_id
            changed_fields.append("verified_job_title")

        employer_comment = getattr(employment_record, "employer_comment", "")
        if employer_comment and not decision.comment:
            decision.comment = employer_comment
            changed_fields.append("comment")

        employment_verified_at = getattr(employment_record, "verified_at", None)
        if employment_verified_at and not decision.decided_at:
            decision.decided_at = employment_verified_at
            changed_fields.append("decided_at")

        if changed_fields:
            decision.save(update_fields=changed_fields)


def _reverse_backfill_verification_outputs(apps, schema_editor):
    # Historical values cannot be safely reconstructed once source fields are removed.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0003_rename_tracer_alum_skill_i_8f7ac2_idx_tracer_alum_skill_i_5c1116_idx_and_more'),
        ('users', '0006_remove_employeraccount_profile_json_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employmentrecord',
            name='tracer_empl_industr_827bf6_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationtoken',
            name='tracer_veri_graduat_36ae49_idx',
        ),
        migrations.RenameField(
            model_name='verificationtoken',
            old_name='graduate',
            new_name='alumni',
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='verified_employer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='verified_job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_decisions', to='tracer.jobtitle'),
        ),
        migrations.RunPython(
            code=_backfill_verification_outputs,
            reverse_code=_reverse_backfill_verification_outputs,
        ),
        migrations.RemoveField(
            model_name='employmentrecord',
            name='employer_comment',
        ),
        migrations.RemoveField(
            model_name='employmentrecord',
            name='employer_name_verified',
        ),
        migrations.RemoveField(
            model_name='employmentrecord',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='employmentrecord',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='verificationdecision',
            name='employment_record',
        ),
        migrations.AddIndex(
            model_name='employmentrecord',
            index=models.Index(fields=['job_title', 'region'], name='tracer_empl_job_tit_2ecad5_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['alumni', 'status'], name='tracer_veri_alumni__6d2ca5_idx'),
        ),
    ]
