# Generated by Django 5.2.13 on 2026-04-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0004_remove_employmentrecord_tracer_empl_industr_827bf6_idx_and_more'),
        ('users', '0007_alter_alumniaccount_biometric_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdecision',
            name='held_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='is_held',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='verificationdecision',
            index=models.Index(fields=['is_held', 'employer_account'], name='tracer_veri_is_held_3b500f_idx'),
        ),
    ]
