# Generated by Django 5.2.13 on 2026-04-21 12:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0005_verificationdecision_held_activated_at_and_more'),
        ('users', '0008_alumniprofile_academic_honors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technical_skills', models.JSONField(blank=True, default=list, help_text='Array of technical skill selections with boolean flags')),
                ('soft_skills', models.JSONField(blank=True, default=list, help_text='Array of soft skill selections with boolean flags')),
                ('technical_skill_count', models.IntegerField(default=0, help_text='Count of selected technical skills (0-12)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('soft_skill_count', models.IntegerField(default=0, help_text='Count of selected soft skills (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('professional_certifications', models.CharField(blank=True, help_text='Comma-separated list of professional certifications', max_length=500)),
                ('assessment_date', models.DateTimeField(auto_now=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_profiles', to='users.alumniaccount')),
            ],
            options={
                'db_table': 'tracer_competency_profiles',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employment_status', models.CharField(blank=True, choices=[('employed_full_time', 'Employed Full-Time'), ('employed_part_time', 'Employed Part-Time'), ('self_employed', 'Self-Employed/Freelance'), ('seeking', 'Seeking Employment'), ('not_seeking', 'Not Seeking Employment')], help_text='Current employment status of alumni', max_length=20, null=True)),
                ('time_to_hire_raw', models.CharField(blank=True, help_text="Original user response for time-to-hire (e.g., '3-6 months')", max_length=50, null=True)),
                ('time_to_hire_months', models.FloatField(blank=True, help_text='Time-to-hire in months (1, 3, 4.5, 9, 18, 30 or NULL if never employed)', null=True)),
                ('first_job_sector', models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('entrepreneurial', 'Entrepreneurial/Freelance/Self-Employed')], help_text='Sector of first job', max_length=20, null=True)),
                ('first_job_status', models.CharField(blank=True, choices=[('regular', 'Regular/Permanent'), ('probationary', 'Probationary'), ('contractual', 'Contractual/Casual'), ('self_employed', 'Self-Employed/Freelance')], help_text='Employment status of first job', max_length=30, null=True)),
                ('first_job_title', models.CharField(blank=True, help_text='Job title of first employment', max_length=150, null=True)),
                ('first_job_related_to_bsis', models.BooleanField(blank=True, help_text='True=Directly related to BSIS, False=Not related, NULL=N/A', null=True)),
                ('first_job_unrelated_reason', models.CharField(blank=True, help_text='Reason why first job is not related to BSIS', max_length=200, null=True)),
                ('first_job_duration_months', models.IntegerField(blank=True, help_text='Duration of first job in months', null=True)),
                ('first_job_applications_count', models.IntegerField(blank=True, help_text='Number of job applications before receiving offer (1-5=1, 6-15=2, 16-30=3, 31+=4)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('first_job_source', models.CharField(blank=True, choices=[('personal_network', 'Personal Network/Referral'), ('online_portal', 'Online Job Portal'), ('career_fair', 'CHMSU Career Fair'), ('walk_in', 'Company Walk-in/Direct Hire'), ('social_media', 'Social Media'), ('entrepreneurship', 'Started own business/Freelance'), ('other', 'Other')], help_text='How the first job was found', max_length=50, null=True)),
                ('current_job_sector', models.CharField(blank=True, help_text='Sector of current/most recent job', max_length=20, null=True)),
                ('current_job_title', models.CharField(blank=True, help_text='Job title of current/most recent employment', max_length=150, null=True)),
                ('current_job_company', models.CharField(blank=True, help_text='Company name of current/most recent employment', max_length=200, null=True)),
                ('current_job_related_to_bsis', models.BooleanField(blank=True, help_text='True=Directly related to BSIS, False=Not related, NULL=N/A', null=True)),
                ('location_type', models.BooleanField(blank=True, help_text='True=Local (Philippines), False=Abroad/Remote, NULL=N/A', null=True)),
                ('survey_completion_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', help_text='Survey completion status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_profiles', to='users.alumniaccount')),
            ],
            options={
                'db_table': 'tracer_employment_profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street_address', models.CharField(blank=True, help_text='Street address (optional)', max_length=200)),
                ('barangay', models.CharField(blank=True, help_text='Barangay (optional)', max_length=100)),
                ('city_municipality', models.CharField(help_text='City/Municipality (required)', max_length=100)),
                ('province', models.CharField(help_text='Province (required)', max_length=100)),
                ('region', models.CharField(choices=[('NCR', '→ NCR'), ('Region I', 'Region I (Ilocos)'), ('Region II', 'Region II (Cagayan Valley)'), ('Region III', 'Region III (Central Luzon)'), ('Region IV-A', 'Region IV-A (CALABARZON)'), ('Region IV-B', 'Region IV-B (MIMAROPA)'), ('Region V', 'Region V (Bicol)'), ('Region VI', 'Region VI (Western Visayas)'), ('Region VII', 'Region VII (Central Visayas)'), ('Region VIII', 'Region VIII (Eastern Visayas)'), ('Region IX', 'Region IX (Zamboanga Peninsula)'), ('Region X', 'Region X (Northern Mindanao)'), ('Region XI', 'Region XI (Davao)'), ('Region XII', 'Region XII (SOCCSKSARGEN)'), ('Region XIII', 'Region XIII (Caraga)'), ('CAR', 'CAR (Cordillera)'), ('BARMM', 'BARMM'), ('Abroad', 'Abroad/International')], help_text='Philippine region or Abroad', max_length=50)),
                ('zip_code', models.CharField(blank=True, help_text='ZIP code (optional)', max_length=20)),
                ('country', models.CharField(default='Philippines', help_text='Country name', max_length=100)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude coordinate', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude coordinate', null=True)),
                ('is_current', models.BooleanField(default=True, help_text='Mark as current work address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_addresses', to='users.alumniaccount')),
                ('employment_profile', models.ForeignKey(blank=True, help_text='Link to employment profile (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_addresses', to='tracer.employmentprofile')),
            ],
            options={
                'db_table': 'tracer_work_addresses',
                'ordering': ['-is_current', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employmentprofile',
            index=models.Index(fields=['alumni', '-updated_at'], name='tracer_empl_alumni__6f4be6_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentprofile',
            index=models.Index(fields=['employment_status'], name='tracer_empl_employm_77e267_idx'),
        ),
        migrations.AddIndex(
            model_name='workaddress',
            index=models.Index(fields=['alumni', '-is_current'], name='tracer_work_alumni__627911_idx'),
        ),
        migrations.AddIndex(
            model_name='workaddress',
            index=models.Index(fields=['region'], name='tracer_work_region_a236e6_idx'),
        ),
    ]
