# Generated by Django 5.2.13 on 2026-05-09 16:37
# Locations refactor: adds Region.psgc_id + new Province / CityMunicipality models.
# (The phantom CompetencyProfile / EmploymentProfile / WorkAddress entries that
# `makemigrations` keeps re-generating were stripped here — those models live
# in earlier migrations already applied to prod.)

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0008_verificationdecision_evaluation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='psgc_id',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('psgc_id', models.CharField(max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='tracer.region')),
            ],
            options={
                'db_table': 'tracer_provinces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CityMunicipality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('psgc_id', models.CharField(max_length=12, unique=True)),
                ('is_city', models.BooleanField(default=False, help_text='True for city/submunicipality, False for municipality.')),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='tracer.region')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='tracer.province')),
            ],
            options={
                'db_table': 'tracer_city_municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['region', 'name'], name='tracer_prov_region__4c32bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='province',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='uniq_province_region_name'),
        ),
        migrations.AddIndex(
            model_name='citymunicipality',
            index=models.Index(fields=['region', 'name'], name='tracer_city_region__990545_idx'),
        ),
        migrations.AddIndex(
            model_name='citymunicipality',
            index=models.Index(fields=['province', 'name'], name='tracer_city_provinc_52c6b6_idx'),
        ),
    ]
