# Generated by Django 5.2.13 on 2026-08-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0009_region_psgc_id_competencyprofile_employmentprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workaddress',
            name='region',
            field=models.CharField(choices=[('NCR', '→ NCR'), ('Region I', 'Region I (Ilocos)'), ('Region II', 'Region II (Cagayan Valley)'), ('Region III', 'Region III (Central Luzon)'), ('Region IV-A', 'Region IV-A (CALABARZON)'), ('Region IV-B', 'Region IV-B (MIMAROPA)'), ('Region V', 'Region V (Bicol)'), ('Region VI', 'Region VI (Western Visayas)'), ('Region VII', 'Region VII (Central Visayas)'), ('Region VIII', 'Region VIII (Eastern Visayas)'), ('Region IX', 'Region IX (Zamboanga Peninsula)'), ('Region X', 'Region X (Northern Mindanao)'), ('Region XI', 'Region XI (Davao)'), ('Region XII', 'Region XII (SOCCSKSARGEN)'), ('Region XIII', 'Region XIII (Caraga)'), ('CAR', 'CAR (Cordillera)'), ('BARMM', 'BARMM'), ('Abroad', 'Abroad/International')], help_text='Philippine region or Abroad', max_length=50),
        ),
    ]
