# Generated by Django 5.2.13 on 2026-08-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0010_alter_workaddress_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='is_bsis_aligned',
            field=models.BooleanField(blank=True, db_index=True, help_text='True when is_field is an IS field, False for non_is, NULL when unclassified.', null=True),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='is_field',
            field=models.CharField(blank=True, choices=[('software_dev', 'Software Development'), ('data_db', 'Data / Database'), ('network_infra', 'Network / Infrastructure'), ('it_support', 'IT Support'), ('systems_analysis', 'Systems Analysis'), ('non_is', 'Outside Information Systems')], db_index=True, help_text='Which IS field this role sits in. NULL = not yet classified.', max_length=20, null=True),
        ),
    ]
