# Generated by Django 5.2.13 on 2026-08-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0011_jobtitle_is_bsis_aligned_jobtitle_is_field'),
        ('users', '0019_alumni_consent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdecision',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='flagged_for_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='verifier_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='verifier_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='verifier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='verifier_position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='verificationdecision',
            name='employer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_decisions', to='users.employeraccount'),
        ),
    ]
