# Generated by Django 5.2.13 on 2026-08-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0012_verificationdecision_flag_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationtoken',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
