# Generated by Django 5.2.13 on 2026-09-14 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0014_employmentprofile_validation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymunicipality',
            name='home_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='independent_cities', to='tracer.province'),
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('psgc_id', models.CharField(max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangays', to='tracer.citymunicipality')),
            ],
            options={
                'db_table': 'tracer_barangays',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'name'], name='tracer_bara_city_id_be1003_idx')],
            },
        ),
    ]
