# Generated by Django 5.2.13 on 2026-09-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0015_citymunicipality_home_province_barangay'),
        ('users', '0021_alumniprofile_profile_names_have_no_digits_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employmentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('time_to_hire_months__isnull', True), ('time_to_hire_months__in', [1, 3, 4.5, 9, 18, 30]), _connector='OR'), name='employment_time_to_hire_is_survey_option'),
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '[[:alpha:]]')), name='industry_name_has_letters'),
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '[[:alpha:]]')), name='job_title_name_has_letters'),
        ),
        migrations.AddConstraint(
            model_name='workaddress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR')), name='work_address_coordinates_on_earth'),
        ),
    ]
