# Generated by Django 5.2.13 on 2026-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0016_employmentprofile_employment_time_to_hire_is_survey_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentprofile',
            name='first_job_company',
            field=models.CharField(blank=True, help_text='Company or organization of first employment', max_length=200, null=True),
        ),
    ]
